<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\JourneyMilestone;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\Rule;

class JourneyMilestoneController extends Controller
{
    /** GET /api/admin/journey-milestones (optional ?track_id filter). */
    public function index(Request $request)
    {
        $query = JourneyMilestone::query()->with(['project', 'technologies']);

        if (! $request->is('api/admin/*')) {
            $query->where('is_active', true);
        }

        if ($request->filled('track_id')) {
            $query->where('track_id', $request->integer('track_id'));
        }

        return $query->orderBy('happened_at')->get();
    }

    /** GET /api/admin/journey-milestones/{milestone}. */
    public function show(JourneyMilestone $milestone): JourneyMilestone
    {
        return $milestone->load(['track', 'project', 'technologies']);
    }

    public function store(Request $request): JsonResponse
    {
        $request->validate($this->rules($request));

        // commit_hash auto-generated by the model's saving hook when omitted.
        $milestone = JourneyMilestone::create($request->all());

        return response()->json($milestone->load(['project', 'technologies']), Response::HTTP_CREATED);
    }

    public function update(Request $request, JourneyMilestone $milestone): JourneyMilestone
    {
        $request->validate($this->rules($request, $milestone));

        $milestone->update($request->all());

        return $milestone->load(['project', 'technologies']);
    }

    public function destroy(JourneyMilestone $milestone): Response
    {
        $milestone->delete();

        return response()->noContent();
    }

    private function rules(Request $request, ?JourneyMilestone $milestone = null): array
    {
        return [
            'track_id' => ['required', 'integer', 'exists:journey_tracks,id'],
            'kind' => ['required', Rule::in(['commit', 'tag', 'merge', 'head'])],
            'commit_hash' => ['nullable', 'string', 'size:7'],
            'title_en' => ['required', 'string', 'max:200'],
            'title_fr' => ['nullable', 'string', 'max:200'],
            'title_ar' => ['nullable', 'string', 'max:200'],
            'body_en' => ['nullable', 'string'],
            'body_fr' => ['nullable', 'string'],
            'body_ar' => ['nullable', 'string'],
            'tag_label' => ['nullable', 'string', 'max:60'],
            'happened_at' => ['required', 'date'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'link_url' => ['nullable', 'url', 'max:500'],
            'is_highlight' => ['boolean'],
            'sort_order' => ['nullable', 'integer', 'min:0'],
            'is_active' => ['boolean'],
        ];
    }
}
